### ISSUE TITLE
Could not open tasty file on Windows

### ISSUE THREAD

**Issue by HalfLegend** [gzoller/scala-reflection#29]
My Code
```
val a = RType.of(classOf[TestEntity])
```
Error:
```
Illegal char <:> at index 2: /E:/Workspace/{hidden}/target/scala-3.1.0/test-classes/{hidden}/TestEntity.tasty
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/Workspace/{hidden}/target/scala-3.1.0/test-classes/{hidden}/TestEntity.tasty
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at dotty.tools.io.Path$.apply(Path.scala:53)
	at scala.tasty.inspector.TastyInspector$.checkFile$1(TastyInspector.scala:44)
	at scala.tasty.inspector.TastyInspector$.inspectAllTastyFiles$$anonfun$1(TastyInspector.scala:49)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.tasty.inspector.TastyInspector$.inspectAllTastyFiles(TastyInspector.scala:49)
	at scala.tasty.inspector.TastyInspector$.inspectTastyFiles(TastyInspector.scala:27)
	at co.blocke.scala_reflection.RTypeOfNoPlugin.of$$anonfun$2$$anonfun$1(RType.scala:71)
	at scala.Option.getOrElse(Option.scala:201)
	at co.blocke.scala_reflection.RTypeOfNoPlugin.of$$anonfun$1(RType.scala:84)
	at scala.collection.mutable.HashMap.getOrElse(HashMap.scala:436)
	at co.blocke.scala_reflection.RTypeOfNoPlugin.of(RType.scala:84)
	at co.blocke.scala_reflection.RType$.of(RType.scala:136)
```

You can see the path is started with "/".

cause: in `co.blocke/scala_reflection/RType.scala` around line 68: 
```
val tastyPath = Option(clazz.getProtectionDomain.getCodeSource).map(src => src.getLocation.getPath + clazz.getName.replace(".","/") + ".tasty")
        tastyPath match {
          case Some(path) if ( new java.io.File(path) ).exists =>
            TastyInspector.inspectTastyFiles(List(path))(tc)
            tc.inspected
          case _ =>
            // Non-Tasty top-level class (Java, or String-marshalled Class)
            val fn = (qctx: Quotes) ?=> RType.unwindType(qctx)( qctx.reflect.TypeRepr.typeConstructorOf(clazz), false )
            val reflectedRType = withQuotes(fn)
```
The tasty path from `clazz.getProtectionDomain.getCodeSource` is started with "/"
The result of ` case Some(path) if ( new java.io.File(path) ).exists` is `true`, because the API is from `java.io`, however `TastyInspector.inspectTastyFiles` uses NIO to open the file and caused error.

Scala Version: 3.1.0
JDK Version: 17
Vendor: OpenJDK

**Comment by pjfanning** [comment]
@HalfLegend could you try https://github.com/gzoller/scala-reflection/pull/30 ?

**Comment by gzoller** [comment]
@HalfLegend, if you can confirm #30 works for you, I'll commit and push a new release.  Sadly I have no Windows machine to test it on.

**Comment by HalfLegend** [comment]
Thank you very much, I am trying, but I'm afraid it is not the best sollution
#30  changed "/" to `File.pathSeparator`, however Windows supports "/" as well, so it is not the root cause.
The **leading "/"** is the root cause of the issue.

Furthermore, I recommend to use NIO to check the existence of a file, like  `Files.exists( xxxx )`

**Comment by HalfLegend** [comment]
@gzoller @pjfanning 
The good news is, it works! Thank you very much.
But I am still curious about the reason. Let me debug for a while

**Comment by HalfLegend** [comment]
```
val tastyPath = Option(clazz.getProtectionDomain.getCodeSource).map(src => src.getLocation.getPath + clazz.getName.replace(".", File.pathSeparator) + ".tasty")
```
This solution is totally wrong.... 
File.pathSeparator is ";"
So the path here is always wrong....
So `case Some(path) if ( new java.io.File(path) ).exists =>` will never match

**Comment by pjfanning** [comment]
@HalfLegend you are the one with a Windows machine - can you try to create a PR that works?

**Comment by HalfLegend** [comment]
@pjfanning Please review my PR #31 
The core logic to resolve tasty file path is in FileResolver

**Comment by HalfLegend** [comment]
Main modification:
I need to remove the leading "/" in the path on Windows，and I don't wan't to remove it on Mac or Linux
If I handle this myself with String, it would be a lot of work. 
I achieved this by  using `Path::normalize`, which will provide me a well-formatted path with a leading "/" on Mac and Linux, and no leading “/” on Windows

Other modifications:
1. sbt updated to 1.6.1 (@pjfanning already done this in #30 )
2. scala version updated to 3.1.0
3. both "with plugin" and "no plugin" are fixed
4. `new java.io.File(path) ).exists` is changed to `Files.exists(path)`  to match the behavior in tasty file inspectation

**Comment by HalfLegend** [comment]
scala verson kept 3.0.2

**Comment by gzoller** [comment]
Great, thank you for looking at this... let me look at the release.  Maybe a day or so--New Years, etc.

**Comment by gzoller** [comment]
I think we'll leave Scala version at 3.0.2 for now.  Let 3.1.0 soak into the ecosystem for a bit.  Next version of this lib, after this one I'm building, will be 3.1.0+.
